/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiayang_so_ModelProcessor */

#ifndef _Included_com_jiayang_so_ModelProcessor
#define _Included_com_jiayang_so_ModelProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiayang_so_ModelProcessor
 * Method:    createHandler
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_jiayang_so_ModelProcessor_createHandler
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jiayang_so_ModelProcessor
 * Method:    destroyHandler
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jiayang_so_ModelProcessor_destroyHandler
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jiayang_so_ModelProcessor
 * Method:    infer
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jiayang_so_ModelProcessor_infer
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_jiayang_so_ModelProcessor
 * Method:    setLicense
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jiayang_so_ModelProcessor_setLicense
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
