/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ModelProcessor */

#ifndef _Included_ModelProcessor
#define _Included_ModelProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ModelProcessor
 * Method:    setLicense
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ModelProcessor_setLicense
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ModelProcessor
 * Method:    createDetectionHandler
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_ModelProcessor_createDetectionHandler
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ModelProcessor
 * Method:    destroyDetectionHandler
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ModelProcessor_destroyDetectionHandler
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ModelProcessor
 * Method:    detectionInfer
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ModelProcessor_detectionInfer
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     ModelProcessor
 * Method:    createClassificationHandler
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_ModelProcessor_createClassificationHandler
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ModelProcessor
 * Method:    destroyClassificationHandler
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ModelProcessor_destroyClassificationHandler
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ModelProcessor
 * Method:    classificationInfer
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ModelProcessor_classificationInfer
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
