/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ModelProcessor */

#ifndef _Included_ModelProcessor
#define _Included_ModelProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ModelProcessor
 * Method:    setLicense
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ModelProcessor_setLicense
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ModelProcessor
 * Method:    createHandler
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ModelProcessor_createHandler
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ModelProcessor
 * Method:    destroyHandler
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ModelProcessor_destroyHandler
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ModelProcessor
 * Method:    infer
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ModelProcessor_infer
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
